IdentityDemo2/Models/Problem.cs
namespace IdentityDemo2.Models
{
    public enum DifficultyLevel
    {
        EASY, MEDIUM, HARD
    }
    public class Problem
    {
        public int Id { get; set; }

   
        public string Title { get; set; }


        public string Description { get; set; }

        public string ProblemStatement { get; set; }
        public string Explanation { get; set; }

         public int Marks { get; set; }

        public DifficultyLevel DifficultyLevel { get; set; }
        public string SampleInput { get; set; }
        public string SampleOutput { get; set; }

        public string Testcase { get; set; }

        public string ResultOfTestCase { get; set; }
        public string SolutionCode { get; set; }


        //Foreign key with contest table
        public int ContestId { get; set; }
        public Contest Contest { get; set; } = null!;


        //Foreign Key for attempt tables
        public ICollection<Attempt> attempt { get; } = new List<Attempt>();




    }
}

IdentityDemo2/Controllers/AttemptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IdentityDemo2.Data;
using IdentityDemo2.Models;
using Microsoft.AspNetCore.Identity;
using IdentityDemo2.Migrations;
using System.Security.Claims;
using Newtonsoft.Json;
using System.Text;
using Newtonsoft.Json;
using IdentityDemo2.DTOs;
using NuGet.Protocol;
using Newtonsoft.Json.Linq;


namespace IdentityDemo2.Controllers
{
    public class AttemptsController : Controller
    {
        private readonly ParikshakDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public AttemptsController(ParikshakDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Attempts
        public async Task<IActionResult> Index()
        {
            var parikshakDBContext = _context.Attempt.Include(a => a.ApplicationUser).Include(a => a.Contest).Include(a => a.Problem);
            return View(await parikshakDBContext.ToListAsync());
        }

        // GET: Attempts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Attempt == null)
            {
                return NotFound();
            }

            var attempt = await _context.Attempt
                .Include(a => a.ApplicationUser)
                .Include(a => a.Contest)
                .Include(a => a.Problem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attempt == null)
            {
                return NotFound();
            }

            return View(attempt);
        }

        // GET: Attempts/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["ContestId"] = new SelectList(_context.Contestes, "Id", "Id");
            ViewData["ProblemId"] = new SelectList(_context.Problemes, "Id", "Id");
            return View();
        }

        // POST: Attempts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Language,SolvedStatus,Result,ObtainedMarks,ApplicationUserId,ContestId,ProblemId")] Attempt attempt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(attempt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", attempt.ApplicationUserId);
            ViewData["ContestId"] = new SelectList(_context.Contestes, "Id", "Id", attempt.ContestId);
            ViewData["ProblemId"] = new SelectList(_context.Problemes, "Id", "Id", attempt.ProblemId);
            return View(attempt);
        }

        // GET: Attempts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Attempt == null)
            {
                return NotFound();
            }

            var attempt = await _context.Attempt.FindAsync(id);
            if (attempt == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", attempt.ApplicationUserId);
            ViewData["ContestId"] = new SelectList(_context.Contestes, "Id", "Id", attempt.ContestId);
            ViewData["ProblemId"] = new SelectList(_context.Problemes, "Id", "Id", attempt.ProblemId);
            return View(attempt);
        }

        // POST: Attempts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Language,SolvedStatus,Result,ObtainedMarks,ApplicationUserId,ContestId,ProblemId")] Attempt attempt)
        {
            if (id != attempt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attempt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttemptExists(attempt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", attempt.ApplicationUserId);
            ViewData["ContestId"] = new SelectList(_context.Contestes, "Id", "Id", attempt.ContestId);
            ViewData["ProblemId"] = new SelectList(_context.Problemes, "Id", "Id", attempt.ProblemId);
            return View(attempt);
        }

        // GET: Attempts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Attempt == null)
            {
                return NotFound();
            }

            var attempt = await _context.Attempt
                .Include(a => a.ApplicationUser)
                .Include(a => a.Contest)
                .Include(a => a.Problem)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (attempt == null)
            {
                return NotFound();
            }

            return View(attempt);
        }

        // POST: Attempts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Attempt == null)
            {
                return Problem("Entity set 'ParikshakDBContext.Attempt'  is null.");
            }
            var attempt = await _context.Attempt.FindAsync(id);
            if (attempt != null)
            {
                _context.Attempt.Remove(attempt);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttemptExists(int id)
        {
            return (_context.Attempt?.Any(e => e.Id == id)).GetValueOrDefault();
        }





        ////*** Viraj working here ***/////////////////////////////////////////////////////////////////


        // GET: Attempts/Create
        /*public IActionResult AttemptProblemCodeIt()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["ContestId"] = new SelectList(_context.Contestes, "Id", "Id");
            ViewData["ProblemId"] = new SelectList(_context.Problemes, "Id", "Id");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AttemptProblemCodeIt([Bind("Code,ApplicationUserId,ContestId,ProblemId")] Attempt attempt)
        {
           
                _context.Add(attempt);
                await _context.SaveChangesAsync();
                return RedirectToAction("");
           
        }*/



        ////*** Viraj Completed ***////////////////////////////////////////////////////////////////////












        ////*** Rushikesh working here ***/////////////////////////////////////////////////////////////
        /* [HttpPost] *OLD CODE*
         [ValidateAntiForgeryToken]
         public async Task<IActionResult> attemptproblem_partial_([Bind("Code")] Attempt attempt, int ProblemId)
         {

             attempt.Language = CodingLanguage.JAVA;
             attempt.SolvedStatus = SolvedStatus.Solved;
             attempt.Result = "PASS";
             attempt.ObtainedMarks = 10;
             attempt.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
             var problem = _context.Problemes.Find(ProblemId);
             attempt.ContestId = problem.ContestId;
             attempt.ProblemId = ProblemId;

             Console.WriteLine("Submitted problem id  : " + attempt.ProblemId + " contest id " + attempt.ContestId);
             Console.WriteLine("Submitted  for user  id: " + attempt.ApplicationUserId);


             _context.Add(attempt);
             await _context.SaveChangesAsync();

             return RedirectToAction(nameof(Index));
         }*/

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> attemptproblem_partial_([Bind("Code")] Attempt attempt, int ProblemId)
        //{
        //    attempt.Language = CodingLanguage.JAVA;
        //    attempt.SolvedStatus = SolvedStatus.Solved;
        //    attempt.Result = "PASS";
        //    attempt.ObtainedMarks = 10;
        //    attempt.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //    var problem = _context.Problemes.Find(ProblemId);
        //    attempt.ContestId = problem.ContestId;
        //    attempt.ProblemId = ProblemId;

        //    Console.WriteLine("Submitted problem id  : " + attempt.ProblemId + " contest id " + attempt.ContestId);
        //    Console.WriteLine("Submitted  for user  id: " + attempt.ApplicationUserId);

        //    // Print the actual content of attempt.Code to the console for debugging
        //    Console.WriteLine($"Code to be submitted:\n{attempt.Code}");

        //    string input = problem.SampleInput;

IdentityDemo2/Views/Problems/AddProblem.cshtml
@model IdentityDemo2.Models.Problem

@{
    ViewData["Title"] = "AddProblem";
}

<h1>AddProblem</h1>

<h4>Problem</h4>
<hr />
<div class="container">
    <form asp-action="AddProblem">
       <div class="row">
           <div class="col-sm">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProblemStatement" class="control-label"></label>
                    <input asp-for="ProblemStatement" class="form-control" />
                    <span asp-validation-for="ProblemStatement" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Explanation" class="control-label"></label>
                    <input asp-for="Explanation" class="form-control" />
                    <span asp-validation-for="Explanation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Marks" class="control-label"></label>
                    <input asp-for="Marks" class="form-control" />
                    <span asp-validation-for="Marks" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DifficultyLevel" class="control-label"></label>
                    <select asp-for="DifficultyLevel" class="form-control">
                        <option value="0">EASY</option>
                        <option value="1">MEDIUM</option>
                        <option value="2">HARD</option>
                    </select>
                    <span asp-validation-for="DifficultyLevel" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SampleInput" class="control-label"></label>
                    <input asp-for="SampleInput" class="form-control" />
                    <span asp-validation-for="SampleInput" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SampleOutput" class="control-label"></label>
                    <input asp-for="SampleOutput" class="form-control" />
                    <span asp-validation-for="SampleOutput" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Testcase" class="control-label"></label>
                    <input asp-for="Testcase" class="form-control" />
                    <span asp-validation-for="Testcase" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ResultOfTestCase" class="control-label"></label>
                    <input asp-for="ResultOfTestCase" class="form-control" />
                    <span asp-validation-for="ResultOfTestCase" class="text-danger"></span>
                </div>
        </div>
           <div class="col-sm">
                <div class="form-group">
                    <label asp-for="SolutionCode" class="control-label"></label>
                    <textarea asp-for="SolutionCode" class="form-control" id="javaCodeEditor" >
                    </textarea>
                    <span asp-validation-for="SolutionCode" class="text-danger"></span>
                </div>
               
           </div>
       </div>
        
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>
<div class="row">
    <div class="col-md-4">
        
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.1/codemirror.min.js"></script>
<!-- Include CodeMirror Java mode -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.1/mode/clike/clike.min.js"></script>
<!-- Initialize CodeMirror on your input field -->
<script>
    var defaultJavaCode = 'public class Main {\n    public static void main(String[] args) {\n        // Your default Java code here\n    }\n}';

    document.addEventListener("DOMContentLoaded", function () {
        var javaCodeEditor = CodeMirror.fromTextArea(document.getElementById('javaCodeEditor'), {
            mode: 'text/x-java',
            theme: 'dracula', // Optional theme
            lineNumbers: true, // Show line numbers
            autofocus: true, // Automatically focus on the editor
        });

        // Set an initial height (adjust as needed)
        javaCodeEditor.setSize(null, "200px");
        javaCodeEditor.setValue(defaultJavaCode);

        // Set the height of CodeMirror to 100% of its container
        function setEditorHeight() {
            var containerHeight = document.querySelector('.col-sm').offsetHeight;
            javaCodeEditor.setSize(null, containerHeight + 'px');
        }

        // Call the function to set the height initially and whenever the window is resized
        setEditorHeight();
        window.addEventListener('resize', setEditorHeight);
    });
</script>

IdentityDemo2/Views/Problems/AttemptProblem.cshtml
@model IdentityDemo2.Models.Problem

@{
    ViewData["Title"] = "AttemptProblem";
}

<style>
    /* Custom CSS styles */
    .section {
        margin-bottom: 20px;
        border: 1px solid #ddd;
        padding: 10px;
    }

    .box {
        display: inline-block;
        border: 1px solid #ddd;
        padding: 10px;
        margin-right: 10px;
        margin-bottom: 10px;
    }

    .title {
        font-size: 18px;
        font-weight: bold;
    }

    .description {
        font-size: 12px;
    }

    .side-by-side {
        display: flex;
    }

        .side-by-side .box {
            flex: 1;
            margin-right: 0;
        }

    /* Additional style for the partial view section */
    .partial-view-container {
        border: 1px solid #ddd;
        padding: 10px;
        margin-bottom: 10px;
    }

    #javaCodeEditor {
        width: 100%;
        height: 400px; /* Adjust the height as needed */
    }

    .submit-button {
        margin-top: 10px;
    }
</style>

<h1>AttemptProblem</h1>

<div class="section">
    <h4>Problem</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <div class="box title">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Title)
                    </dd>
                </div>

                <div class="box description">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                </div>

                <div class="box description">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.ProblemStatement)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ProblemStatement)
                    </dd>
                </div>

                <div class="box description">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Explanation)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Explanation)
                    </dd>
                </div>

                <div class="box side-by-side">
                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Marks)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Marks)
                        </dd>
                    </div>

                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.DifficultyLevel)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.DifficultyLevel)
                        </dd>
                    </div>
                </div>

                <!-- Add similar boxes for other sections -->

                <div class="box side-by-side">
                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.SampleInput)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.SampleInput)
                        </dd>
                    </div>

                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.SampleOutput)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.SampleOutput)
                        </dd>
                    </div>
                </div>

                <div class="box side-by-side">
                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Testcase)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Testcase)
                        </dd>
                    </div>

                    <div class="col-sm-6">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.ResultOfTestCase)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.ResultOfTestCase)
                        </dd>
                    </div>
                </div>

                <!-- Add similar boxes for other sections -->
            </div>

            <div class="col-sm">
                <div class="partial-view-container">
                    @{
                        Html.RenderPartial("attemptproblem_partial_", Model.attempt.FirstOrDefault());
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IdentityDemo2/Views/Problems/ContestProblemsList.cshtml
@model IEnumerable<IdentityDemo2.Models.Problem>

@{
    ViewData["Title"] = "ContestProblemsList";
}

<h1>ContestProblemsList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProblemStatement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Explanation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marks)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DifficultyLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SampleInput)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SampleOutput)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Testcase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResultOfTestCase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SolutionCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contest)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProblemStatement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Explanation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DifficultyLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SampleInput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SampleOutput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Testcase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResultOfTestCase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contest.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

IdentityDemo2/Views/Problems/attemptproblem_partial_.cshtml
@model IdentityDemo2.Models.Attempt

<div style="display: flex; flex-direction: column;">
    @{
        var problem_id = Context.Request.Query["problemId"];
    }
    <form asp-controller="Attempts" asp-action="attemptproblem_partial_" asp-route-ProblemId=@problem_id >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*         <h1>Problem Id : @problem_id</h1>
 *@            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <textarea asp-for="Code" class="form-control" id="javaCodeEditor">
                    </textarea>

                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            
        </form>

    <div class="" style="margin-top: 10px; align-self: flex-end;">
        <input type="button" value="Submit" id="submitButton" class="btn btn-primary" onclick="callCustomMethod()" />
        <div id="loadingSpinner" style="display: none;">Loading...</div>

    </div>

    <h4 id="submissionstatus"></h4>
    <pre id="submissionoutput"></pre>

    
</div>


@* //Not Required Back to List
<div>
    <a asp-action="Index">Back to List</a>
</div> *@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<!-- Add the link tag for the Dracula theme here 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.1/theme/dracula.min.css"> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.1/codemirror.min.js"></script>
<!-- Include CodeMirror Java mode -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.1/mode/clike/clike.min.js"></script>
<!-- Initialize CodeMirror on your input field -->
<script>
    var defaultJavaCode = 'import java.util.Scanner;\npublic class Main {\n    public static void main(String[] args) {\n           Scanner sc = new Scanner(System.in);\n        // Your default Java code here\n    }\n}';
   
    var javaCodeEditor;

    document.addEventListener("DOMContentLoaded", function () {

        var container = document.querySelector('.col-sm');
        var initialHeight = 300;  // Adjust the initial height value as needed

        javaCodeEditor = CodeMirror.fromTextArea(document.getElementById('javaCodeEditor'), {
            mode: 'text/x-java',
            theme: 'dracula', // Optional theme
            lineNumbers: true, // Show line numbers
            autofocus: true, // Automatically focus on the editor
        });

        // Set the editor height explicitly
        javaCodeEditor.setSize(null, initialHeight + 'px');
        javaCodeEditor.setValue(defaultJavaCode);

        

        // Call the function to set the height initially and whenever the window is resized
       
        window.addEventListener('resize', setEditorHeight);
    });

    // Set the height of CodeMirror to 100% of its container
    function setEditorHeight() {
        var containerHeight = document.querySelector('.col-sm').offsetHeight;
        javaCodeEditor.setSize(null, containerHeight + 'px');
    }


    function callCustomMethod() {
        var javaCode = getCodeFromEditor();
        var problemId = '@problem_id';

        document.getElementById('submitButton').disabled = true;
        document.getElementById('loadingSpinner').style.display = 'block';

        fetch(`/Attempts/AttemptSubmission?ProblemId=${problemId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ Code: javaCode })
        })
            .then(response => {
                if (response.ok) {
                    return response.json(); // Parse the JSON response
                } else {
                    throw new Error('Error calling custom method');
                }
            })
            .then(data => {
                // Update the HTML elements with the received data
                document.getElementById('submissionstatus').textContent = `Status: ${data.status}`;
                document.getElementById('submissionoutput').textContent = `Output: ${data.message}`;

                // Enable the submit button and hide loading spinner
                if (data.status != "Submitted : Sample Testcases and Hidden Testcases passed")
                    document.getElementById('submitButton').disabled = false;
                document.getElementById('loadingSpinner').style.display = 'none';
            })
            .catch(error => {
                console.error('Error:', error);

                // Enable the submit button and hide loading spinner
                document.getElementById('submitButton').disabled = false;
                document.getElementById('loadingSpinner').style.display = 'none';
            });
    }

    function getCodeFromEditor() {
        // Function to get the code from the CodeMirror editor
         // Use CodeMirror's API to get the value

        return javaCodeEditor.getValue();
    }


</script>